# Use an official Node.js runtime as a parent image
FROM node:22.21-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production && npm cache clean --force

COPY src ./src

USER node

EXPOSE 3000

CMD ["npm", "start"]