# Use an official Node.js runtime as a parent image
FROM node:22.21-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install --only=production && npm cache clean --force

# Copy the rest of the application code
COPY src ./src

USER node

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD ["npm", "start"]