---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: task-manager
  namespace: flux-system
spec:
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./_infra/task-manager
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: task-manager
  values:
    image:
      repository: ghcr.io/sam-viz/playground-helm/task-manager
      tag: sha-06c9bf4 # {"$imagepolicy": "flux-system:task-manager"} 
