---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: task-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./_infra/task-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: task-manager
  values:
    image:
      tag: "9b449b3"
    test:
      image:
        tag: "9b449b3"
